# Generated by Django 5.0.4 on 2024-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(blank=True, default='', max_length=100)),
                ('campus_id', models.IntegerField(blank=True, default='')),
                ('state', models.CharField(blank=True, default='', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'University Campus',
            },
        ),
    ]
